<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>

<?php

$helper = $block->googleMapsStoreHelper;
      $storeImage = $helper->getGMapStoreImage();
      $markerImage = $helper->getGMapMarkerImage();   
      $mediaUrl = $block->getMediaUrl();
      $gMapTagUrl = $helper->getGMapTagUrl();
      $fbCommentsEnable = $helper->getGMapFBCommentsEnable();
      $fbAppID = $helper->getGMapFBAppID();
      
      
      
      if(!$storeImage):
        $storeImage = $block->getViewFileUrl('FME_StorePickup::images/store_icon.png');
      else:
        $storeImage =  $mediaUrl.$helper->getGMapStoreImage();
      endif;
      if(!$markerImage):
        $markerImg = $block->getViewFileUrl('FME_StorePickup::images/marker.png');
      else:
         $markerImg = $mediaUrl.$markerImage;
         $markerImg = $helper->resize($markerImage,55,55);    
      endif;
 ?> 

 
<?php if($helper->getGMapAPIKey()): ?>
    <script 
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo $helper->getGMapAPIKey(); ?>&libraries=places,geometry">
    </script>
     <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>

  <?php else: ?>
    <script 
        src="https://maps.googleapis.com/maps/api/js?libraries=places,geometry">
    </script>
     <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>

  <?php endif;?>
<?php
if($helper->isEnabledInFrontend()):
  $Stores = $this->getAllStores();
  $currentStores = $this->getAllStores()->getFirstItem();
    if($Stores){
	     foreach($Stores as $key => $value){
	         $Storesdescription = $helper->getGMapMetadescription();          
	       }
       }      
     $standard_lat = $helper->getGMapStandardLatitude();
     $standard_long = $helper->getGMapStandardLongitude();
     $standard_zoom = $helper->getGMapZoom();?>
<script>   
    directionsService = new google.maps.DirectionsService();
    var geocoder = new google.maps.Geocoder();
    markerImg = '<?php echo $markerImg; ?>';
    distUnit = 'km';  
    var map = null;
    var circle = null;
    var gmarkers = '';
    
    function initMap(sel) {
            
            directionsDisplay = new google.maps.DirectionsRenderer();
            myData = '';        
            var locations, i,j;
            var locations = <?php echo json_encode($Stores->getData()) ?>; 
            
            for(j=0; j< locations.length; j++){
                var gid = locations[j]['gmaps_id'];  
                var lat = locations[j]['latitude'];
                var lng = locations[j]['longitude'];
                var title = locations[j]['store_name'];         
                var description = locations[j]['store_description'];
                var mmzoomlevel = locations[j]['zoom_level'];

            }
          
            var lat = <?php echo $currentStores->getLatitude() ?>;
            var lng = <?php echo $currentStores->getLongitude() ?>;
            var mmzoomlevel = <?php echo  $currentStores->getZoomLevel() ?>;
                           
            var uluru = {lat: eval(lat),lng: eval(lng) };
             map = new google.maps.Map(document.getElementById('map_canvas'), {
                zoom: eval(mmzoomlevel),
                mapTypeIds: google.maps.MapTypeId.ROADMAP,
                center: uluru                
            });
            
            directionsDisplay.setMap(map);

            var locations, i;
            var locations = <?php echo json_encode($Stores->getData()) ?>;
            var contentString = new Array(""); 
            
            gmarkers = [];
            
            var infowindow = new google.maps.InfoWindow();
            for (i = 0; i < locations.length; i++) {

                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i]['latitude'], locations[i]['longitude']),
                    map: map,
                    icon: markerImg,               
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });
                gmarkers.push(marker);

                contentString[i] = '<div id="content">'+
                '<div id="siteNotice">'+
                '</div>'+
                '<h3 id="firstHeading" class="firstHeading">'+locations[i]['store_name']+'</h3>'+
                '<div id="bodyContent">'+locations[i]['store_description']+'</div>'+
                '</div>';

                google.maps.event.addListener(marker, 'click', (function(marker,i) {  
                   return function() {  
                       var content = contentString;

                       infowindow.setContent(contentString[i]);  
                       infowindow.open(map, marker);  
                   }  
                })(marker,i));
            }
            
            var mcOptions = {gridSize: 50, maxZoom: 6, imagePath:'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'};
            var markerCluster = new MarkerClusterer(map, gmarkers, mcOptions);
    }

    function calcRoute(lati,logno,id) {

        initMap();
        require(["jquery"],function($) {
            $(document).ready(function($) {
                var selectedMode =   $('input[name=directionby'+id+']:checked').val();  
                center =document.getElementById('direction'+id).value;
                address=center.replace("-", ""); 
                address=address.replace("-", ""); 

                geocoder.geocode({'address': address}, function(results, status) {
                if (status === google.maps.GeocoderStatus.OK) {
                  var addLati = results[0].geometry.location.lat();
                  var addLongi = results[0].geometry.location.lng();
                  var request = {
                      destination: new google.maps.LatLng(lati,logno),
                      origin  :  new google.maps.LatLng(addLati,addLongi),
                      travelMode: google.maps.TravelMode[selectedMode]
                  };
                  directionsService.route(request, function(response, status) {
                    if (status == google.maps.DirectionsStatus.OK) {
                      var textdirection = document.getElementById('showdirectionText'+id);
                        textdirection.innerHTML= "";
                        textdirection.innerHTML +='<div class="directionblock">Distance: '+response.routes[0].legs[0].distance.value/1000+' KM Duration:'+response.routes[0].legs[0].duration.text+'</div>'; 
                        for (var i =0; i < response.routes[0].legs[0].steps.length; i++){
                            textdirection.innerHTML+='<div class="directionblock">'+response.routes[0].legs[0].steps[i].instructions+"</div>"
                        }
                        textdirection.style.display='block';
                      directionsDisplay.setDirections(response);

                    }
                  });
                }else {
                  return;
                } 

                });
            });
        });

    }

    function streetview(lat,lang)
    {
        panorama = new google.maps.StreetViewPanorama(
        document.getElementById('map_canvas'),
        {
            position: {lat: lat, lng: lang},
            pov: {heading: 165, pitch: 0},
            zoom: 1
        });
    }


    function codeAddress() {
        var address = document.getElementById('searchstore').value;
        var radius = parseInt(document.getElementById('radius').value, 10)*1000;
        geocoder.geocode( { 'address': address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                side_bar_html = "";
                map.setCenter(results[0].geometry.location);
                var searchCenter = results[0].geometry.location;
                if (circle) circle.setMap(null);
                circle = new google.maps.Circle({center:searchCenter,
                                                 radius: radius,
                                                 fillOpacity: 0.35,
                                                 fillColor: "#FF0000",
                                                 map: map});
                var bounds = new google.maps.LatLngBounds();
                var foundMarkers = 0;

                for (var i=0; i<gmarkers.length;i++) {

                  if (google.maps.geometry.spherical.computeDistanceBetween(gmarkers[i].getPosition(),searchCenter) < radius) {
                    bounds.extend(gmarkers[i].getPosition())
                    gmarkers[i].setMap(map); 
                    foundMarkers++;
                  } else {
                    if (gmarkers[i] && gmarkers[i].setMap) {
                        gmarkers[i].setMap(null);
                    }

                  }
                }
                if (foundMarkers > 0) {
                  map.fitBounds(bounds);
                } else {
                  map.fitBounds(circle.getBounds());
                }
            } else {
                alert('Geocode was not successful for the following reason: ' + status);
            }
        });
    }
    
 
</script>

<div class="google_map_locator">
  <h2><?php echo $currentStores->getStoreName(); ?> </h2>
 

<div class="search_content_block">
<div class="buttons_container store_info">
     <a href="<?php echo $block->getUrl().$helper->getGMapLink(); ?>"> <button><?php echo __('Back');?></button></a>
    </div>
<div class="clear"></div>
</div>
<div class="stores_container">
    <div class="stores_list">       

        <div class="total_maps store_title" id="total_maps">
          <?php echo __('Store  Information'); ?>
        </div>   
<div class="store_block store_info">      
           <ul>
                    <?php $i=0; $n=1; foreach($Stores as $s_value): ?>
                    <li class="<?php if($n%2==0):  echo 'white'; endif; ?>" id="stores"> 
                      <div class="store clearfix">
                        <div class="storeThumnb">
                          <img src="<?php echo $storeImage; ?>" >
                        </div>  
                        <div class="store_content">     
                        <?php  $xval= $s_value->getGmapsId()?>
                          <input type="hidden" name="values" id="<?php echo $i ?>"  value="<?php echo $xval;?>">
                          <a href="<?php echo $block->getStoresUrl($s_value->getIdentifier()); ?>" title="<?php echo $s_value->getStoreName(); ?>"><?php echo $s_value->getStoreName(); ?></a>
                          <p><?php echo $s_value->getAddress(); ?></p>
                          <p><?php echo __('Phone No:') ?> <?php echo $s_value->getStorePhone(); ?></p>
                          <p><a href="javascript:void(0)" onclick="streetview(<?php echo $s_value->getLatitude(); ?>,<?php echo $s_value->getLongitude(); ?>)">Street</a> &nbsp; | &nbsp;<a href="javascript:void(0)" >Direction</a></p>
                        </div>
                         <div class="clearfix"></div>
                          <div class="direction clearfix">
                            <div class="direction">
                            <div class="dir_option clearfix">
                              <input type="radio" name="directionby<?php echo $xval; ?>" id="driving" value="DRIVING" checked="checked"><label for="driving"><?php echo __('DRIVING'); ?></label>
                              <input type="radio" name="directionby<?php echo $xval; ?>" id="transit" value="TRANSIT"><label for="transit"><?php echo __('Transit'); ?></label>
                              <input type="radio" name="directionby<?php echo $xval; ?>" id="walking" value="WALKING"><label for="walking"><?php echo __('Walking'); ?></label>
                              <input type="radio" id="Bicycling" name="directionby<?php echo $xval; ?>" value="BICYCLING"><label for="Bicycling"><?php echo __('BICYCLING'); ?></label>
                            </div>
                            <div class="input_container">
                              <input type="text" name="direction<?php echo $xval; ?>" id="direction<?php echo $xval; ?>" autocomplete="off">
                              <script type="text/javascript">
                                function initit<?php echo $xval; ?>() {
                                var options = {
                            
                                 };
                                  var input = document.getElementById('direction<?php echo $xval; ?>');
                                  var autocomplete = new google.maps.places.Autocomplete(input,options);
                              }
              
                              google.maps.event.addDomListener(window, 'load', initit<?php echo $xval; ?>);
                              </script>
                              <input type="text" autocomplete="off" name="current_direction" value="<?php echo $s_value->getAddress(); ?>" readonly="true">
                              <button type="button" onclick="calcRoute(<?php echo $s_value->getLatitude(); ?>,<?php echo $s_value->getLongitude(); ?>,<?php echo $xval; ?>)" ><?php echo __('Go');?></button>
                            </div>
                            <div id="showdirectionText<?php echo $xval; ?>" class="address_direction_block"></div>
                          </div>
                        </div>
                      </div> 
                    </li>
                        <?php $i++;$n++; endforeach; ?>          
                 </ul>       
        </div>
        <?php $tags = $block->getStoresTages($currentStores->getId());

        if($tags->getData()): ?>
        <div class="store_title"> <?php echo __('Tags');?> </div>
          <div class="tags_block">
            <ul>
              <?php 
      foreach ($tags as $tag):
      ?>
     <li> <a href="<?php echo $block->getUrl($gMapTagUrl.'/'.str_replace(' ','-', $tag->getTagName())) ?>"><?php echo $tag->getTagName() ?></a></li> 
      <?php
      endforeach;
        ?>
            
            </ul>
          </div>
        <?php endif; ?>
 <?php $timetable = $this->getStoresHours($currentStores->getTimetableId()); 
          if($timetable->getData()): 
          ?>
        <div class="total_maps store_title" >
          <?php echo __('Opening Hour'); ?> 
        </div>   
        <div class="clear"></div>
        <div class="opening_hours_block">
         
          <table>
            <tr><th><?php echo __('Day'); ?></th><th><?php echo __('Working Hours'); ?></th><th><?php echo __('Break'); ?></th></tr>
            <tr><th><?php echo __('Monday'); ?></th><td>
              <?php if($timetable->getMondayStatus()): 
echo date('H:i A', strtotime($timetable->getMondayOpenTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getMondayCloseTime())); ?></td><td>
              <?php 
echo date('H:i A', strtotime($timetable->getMondayBreakTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getMondayOffbreakTime())); ?></td>
<?php
               else: ?> <td colspan="2"> <?php echo __('Closed'); ?></td><?php
               endif; ?>   
            </td></tr>
            <tr><th><?php echo __('Tuesday'); ?></th><td>
              <?php if($timetable->getTuesdayStatus()): 
echo date('H:i A', strtotime($timetable->getTuesdayOpenTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getTuesdayCloseTime())); ?></td><td>
              <?php 
echo date('H:i A', strtotime($timetable->getTuesdayBreakTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getTuesdayOffbreakTime())); ?></td>
<?php
               else: ?> <td colspan="2"> <?php echo __('Closed'); ?></td><?php
               endif; ?>   
            </td></tr>
            <tr><th><?php echo __('Wednesday'); ?></th><td>
              <?php if($timetable->getWednesdayStatus()): 
echo date('H:i A', strtotime($timetable->getWednesdayOpenTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getWednesdayCloseTime())); ?></td><td>
              <?php 
echo date('H:i A', strtotime($timetable->getWednesdayBreakTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getWednesdayOffbreakTime())); ?></td>
<?php
               else: ?> <td colspan="2"> <?php echo __('Closed'); ?></td><?php
               endif; ?>   
            </td></tr>
            <tr><th><?php echo __('Thursday'); ?></th><td>
              <?php if($timetable->getThursdayStatus()): 
echo date('H:i A', strtotime($timetable->getThursdayOpenTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getThursdayCloseTime())); ?></td><td>
              <?php 
echo date('H:i A', strtotime($timetable->getThursdayBreakTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getThursdayOffbreakTime())); ?></td>
<?php
               else: ?> <td colspan="2"> <?php echo __('Closed'); ?></td><?php
               endif; ?>   
            </td></tr>
            <tr><th><?php echo __('Friday'); ?></th><td>
              <?php if($timetable->getFridayStatus()): 
echo date('H:i A', strtotime($timetable->getFridayOpenTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getFridayCloseTime())); ?></td><td>
              <?php 
echo date('H:i A', strtotime($timetable->getFridayBreakTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getFridayOffbreakTime())); ?></td>
<?php
               else: ?> <td colspan="2"> <?php echo __('Closed'); ?></td><?php
               endif; ?>   
            </td></tr>
            <tr><th><?php echo __('Saturday'); ?></th><td>
              <?php if($timetable->getSaturdayStatus()): 
echo date('H:i A', strtotime($timetable->getSaturdayOpenTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getSaturdayCloseTime())); ?></td><td>
              <?php 
echo date('H:i A', strtotime($timetable->getSaturdayBreakTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getSaturdayOffbreakTime())); ?></td>
<?php
               else: ?> <td colspan="2"> <?php echo __('Closed'); ?></td><?php
               endif; ?>   
            </td></tr>
             <tr><th><?php echo __('Sunday'); ?></th><td>
              <?php if($timetable->getSundayStatus()): 
echo date('H:i A', strtotime($timetable->getSundayOpenTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getSundayCloseTime())); ?></td><td>
              <?php 
echo date('H:i A', strtotime($timetable->getSundayBreakTime()));
echo '&nbsp;&nbsp;&nbsp;';
echo date('H:i A', strtotime($timetable->getSundayOffbreakTime())); ?></td>
<?php
               else: ?> <td colspan="2"> <?php echo __('Closed'); ?></td><?php
               endif; ?>   
            </td></tr>
          </table>
        
        </div>
        <?php endif; ?>
        <?php $holidays = $block->getStoresHolidays($currentStores->getId());

        if($holidays->getData()): ?>
         <div class="total_maps store_title" >
         <?php echo __('Holiday'); ?> 
        </div>   
        <div class="clear"></div>
        <div class="opening_hours_block">
          <table>
          <?php
          
           foreach ($holidays as $holiday) {
            ?>
            <tr><td><b><?php echo $holiday->getHolidayName(); ?></b></td>
              <td>
              <?php 
echo date('d/m/Y ', strtotime($holiday->getHolidayStartFrom()));
echo '&nbsp;-&nbsp;';
echo date('d/m/Y', strtotime($holiday->getHolidayEndsTo())); ?></td></tr>
            <?php
          }
          ?>
        </table>
        </div>
      <?php endif;?>
</div>  
<div class="map_locator_rightside">
<div class="map" >         
      <div id="map_canvas" style="height:550px;" ></div></div>
      <div class="content"><p><?php echo $currentStores->getStoreDescription(); ?></p>
        </div>
        <?php
    if ($exist = ($block->getStoresProducts($currentStores->getId()) && $block->getStoresProducts($currentStores->getId())->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getStoresProducts($currentStores->getId());

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

?>               

    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($currentStores->getStoreName()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($currentStores->getStoreName())).' '.__('Products') ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if ($iterator++ != 1): ?></li><?php endif ?>
                        <li class="product-item productsold">
                           
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($listBlock->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $listBlock->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($listBlock->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?=
                                   $listBlock->getProductPrice($_item);
                                ?>

                                <?php if ($templateType): ?>
                                    <?= $listBlock->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($listBlock->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $listBlock->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($listBlock->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary" data-post='<?= /* @noEscape */ $postData ?>' type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $listBlock->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtml(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($listBlock->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtml(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif;?>    
 </div> 
  </div> 
   </div>    

<script type="text/javascript">
  require(['jquery', 'jquery/ui'], function($){
    
        $(document).ready(function(){
            
            initMap();
           
        });
    
  });
              
</script>
<?php endif; ?>



<div class="google_map_locator_detail">

    <?php if($fbCommentsEnable): ?>
    <div class="fb-container">
        <script async defer src="https://connect.facebook.net/en_US/sdk.js"></script>   
        <script>
          window.fbAsyncInit = function() {
                        FB.init({
                          appId            : '<?php echo $fbAppID ?>',
                          autoLogAppEvents : true,
                          xfbml            : true,
                          version          : 'v3.2'
                        });
            };
        </script>
        <div id="fb-root"></div>
        <div class="fb-comments" data-href="<?php echo $block->getStoresUrl($currentStores->getIdentifier()); ?>" data-width="100%" data-numposts="5"></div>
    </div>
    <?php endif; ?>

    <div class="contact-container">
        
    </div>
</div>    