<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:49
 */
?>
<?php
/**
 * Categories block
 *
 * @var $block \Magepow\Categories\Block\Categories
 */

$categories       = $block->getCategories();
$layout           = $block->getLayout();
$heading          = $block->getHeading();
$description      = $block->isShowDescription();

?>
<?php if (empty($categories)) return ?>
<?php if ($heading): ?>
    <h3 class="magepow-categories-heading"><?php echo $heading ?></h3>
<?php endif; ?>
<section class="widget box-section block-recent-posts" data-bind="scope: 'recemt-posts'">
    <div class="container"> 
        <div class="owl-container">
        	<div class="block-content">
                <ul class="tabs tabs-categories_tab">
                    <div id="catlist" class="owl-carousel">
                    <?php foreach ($categories as $cat): ?>
                      <div class="item">
                        <li>
                			<a href="<?php echo $cat->getUrl() ?>">
                            <img class="categories-thumb-icon" src="<?php echo $this->getImage($cat) ?>" alt="<?php echo $cat->getName() ?>"><h3 class="cnt"><?php echo $cat->getName() ?></h3> </a>
                        </li>
                      </div>
                    <?php endforeach; ?>
                    </div>
                </ul>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery("#catlist").owlCarousel({
		    lazyLoad: true,
			autoPlay : false,
			items : 4,
			itemsDesktop : [1199,4],
			itemsDesktopSmall : [980,4],
			itemsTablet: [768,3],
			itemsMobile : [479,2],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			addClassActive: true,
			navigation : true,
			stopOnHover : true,
			pagination : false,
			scrollPerPage:true,
		});
	});
	</script>
	