<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View\RelatedPosts
 */
  $_post = $this->getPost();
  $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
  $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
  $currentStore = $storeManager->getStore();
  $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="block related">
        <div class="block-title title">
            <h2 id="block-relatedposts-heading" role="heading" aria-level="2">
                <?php echo __('You Might Also Like') ?>
            </h2>
        </div>
        <ol class="block-content">
            <?php foreach ($_postCollection as $_post) { ?>
                <li class="item">	
                    <a href="<?php echo $_post->getPostUrl() ?>">
                        <img src="<?php echo $mediaUrl.$_post->getDetailimage() ?>"/>
                    </a> 
                    <div class="post-date"><strong><?php echo date('d', strtotime($_post->getPublishTime())); ?>, </strong><span><?php echo date('M, Y', strtotime($_post->getPublishTime())); ?></span>
                    </div>
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()); ?>
                    </a>
                </li>
            <?php } ?>
        </ol>
    </div>
	
    <?php } ?>
<?php } ?>