<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
	<div class="item-post-full col-sm-12 block-content post-holder-<?php echo $_post->getId() ?>">
		<div class="blog-post-thumb">
			<div class="zoom-image-thumb">
				<a href="<?php echo $_post->getPostUrl() ?>">
					<img alt="<?php echo $_postName; ?>" src="<?php echo $this->getMediaFolder().$_post->getDetailimage() ?>"/>
				</a>
			</div>		
		</div>
		<div class="post-info">
			<div class="post-info-extra">
				<div class="post-tags-info">
					<?php echo $this->getInfoHtml() ?>
				</div>
				<div class="post-date">/ <strong><?php echo date('d', strtotime($_post->getPublishTime())); ?>, </strong><span><?php echo date('M, Y', strtotime($_post->getPublishTime())); ?></span></div>	
			</div>
			<h3 class="post-title"><a title="<?php echo $_postUrl ?>" href="<?php echo $_postUrl ?>"> <?php echo $_postName; ?></a></h3>
			<div class="short-des">
				<?php echo $_post->getShortContent() ?>
			</div>
			<div class="readmore clearfix">
				<a href="<?php echo $_post->getPostUrl() ?>" class="readmore-text"><?php echo __('Read More');?></a>
				
			</div>
		</div>
	</div>