

<?php
	$enable = $this->getConfig('enable_frontend');
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('default');
	$desktop = $this->getConfig('desktop');
	$desktop_small = $this->getConfig('desktop_small');
	$tablet = $this->getConfig('tablet');
	$mobile = $this->getConfig('mobile');
	$pagination = $this->getConfig('pagination');
	$show_next_back = $this->getConfig('show_next_back');
	$show_navigation_control = $this->getConfig('show_navigation_control');
	$title = $this->getConfig('title');
	$description = $this->getConfig('blog_description');
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = $this->getConfig('show_navigation_control');
	if($show_navigation_control)
		$show_navigation_control = 'true';
	else
		$show_navigation_control = 'false';
	$_postCollection = $block->getPostCollection();
?>

		<div class="owl-container">
			<div class="block-content">
				<div class="owl">
					
						<div class="item">
							<div class="product-item">
								<div class="blog-image">
									<a href="<?php echo $_post->getPostUrl() ?>">
									asdasd
									</a>
									
								</div>
								<div class="blog-content">
									<div class="time-conment">
									
										
									</div>
									<div class="blog-content-inner">
										 <h3 class="blog-title"><a href="">bbbbbbbbbbbbbb</a></h3> 	
										<p class="short-des">cccccccc</p>
										<a class="readmore" href="">
											<?php echo __('Read more') ?>
										</a>
									</div>
								</div>
							</div>
						</div>
						
												<div class="item">
							<div class="product-item">
								<div class="blog-image">
									<a href="<?php echo $_post->getPostUrl() ?>">
									asdasd
									</a>
									
								</div>
								<div class="blog-content">
									<div class="time-conment">
									
										
									</div>
									<div class="blog-content-inner">
										 <h3 class="blog-title"><a href="">bbbbbbbbbbbbbb</a></h3> 	
										<p class="short-des">cccccccc</p>
										<a class="readmore" href="">
											<?php echo __('Read more') ?>
										</a>
									</div>
								</div>
							</div>
						</div>
						
												<div class="item">
							<div class="product-item">
								<div class="blog-image">
									<a href="<?php echo $_post->getPostUrl() ?>">
									asdasd
									</a>
									
								</div>
								<div class="blog-content">
									<div class="time-conment">
									
										
									</div>
									<div class="blog-content-inner">
										 <h3 class="blog-title"><a href="">bbbbbbbbbbbbbb</a></h3> 	
										<p class="short-des">cccccccc</p>
										<a class="readmore" href="">
											<?php echo __('Read more') ?>
										</a>
									</div>
								</div>
							</div>
						</div>
					
				</div>
			</div>
		</div>


<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery(".block-recent-posts .owl").owlCarousel({
			items : <?php echo $default; ?>,
			itemsDesktop : [1199,<?php echo $desktop; ?>],
			itemsDesktopSmall : [980,<?php echo $desktop_small; ?>],
			itemsTablet: [768,<?php echo $tablet; ?>],
			itemsMobile : [479,<?php echo $mobile; ?>],
			slideSpeed : <?php echo $pagination; ?>,
			paginationSpeed : <?php echo $pagination; ?>,
			rewindSpeed : <?php echo $pagination; ?>,
			addClassActive: true,
			navigation : <?php echo $show_next_back; ?>,
			stopOnHover : true,
			pagination : <?php echo $show_navigation_control; ?>,
			scrollPerPage:true,
		});
	});
</script>