<?php 
	use Magento\Framework\App\Action\Action;
	$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = $block->getSlideRow();
	$slide_limit = $block->getSlideLimit();
	$title = $block->getTitle(); 
	$description= $block->getDescription(); 
	$identify = trim($block->getIdentify()); 
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);	
	$desktop = $this->getConfig('itemsDesktop');
	$desktop_small = $this->getConfig('itemsDesktopSmall');
	$tablet = $this->getConfig('itemsTablet');
	$mobile = $this->getConfig('itemsMobile');
?>
<?php 
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('itemsDefault');
	$desktop = $this->getConfig('itemsDesktop');
	$desktop_small = $this->getConfig('itemsDesktopSmall');
	$tablet = $this->getConfig('itemsTablet');
	$mobile = $this->getConfig('itemsMobile');
	$show_next_back = $this->getConfig('next_back');
	$show_navigation_control = $this->getConfig('nav_ctrl');

	use Magento\Framework\App\Action\Action;
	if($this->getConfig('enabled')){ // start enable module?>
		<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');	
?>

<div class="categorytab-container">
	<header class='group-title1'>
		<?php echo '<h2>'.$title.'</h2>'; ?>
		<?php echo '<p class="description">'.$description.'</p>'; ?>
	</header>
  <ul class="tabs tabs<?php echo '-'.$identify;?>"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$newItems =  $block -> getProductCate($cate_id)->getItems();
		$cate_model =  $block->getCategory($cate_id);
		$category_load = $cate_model->load($cate_id);
		$rt_menu_icon_img = $cate_model->getData('rt_menu_icon_img');
		$pathicon = $storeManager->getStore()->getBaseUrl(
                        \Magento\Framework\UrlInterface::URL_TYPE_MEDIA
                ) . 'catalog/category/' . $rt_menu_icon_img;
		$cateName = $category_load->getName();
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>" rel="tab<?php echo $cate_id.'-'.$identify;?>">
				<a href="#">
					<?php if ( $rt_menu_icon_img ): ?>
					<img class="menu-thumb-icon" src="<?php echo $pathicon; ?>" alt="<?php echo $cateName; ?>" />
					<?php endif; ?>
					<?php  echo $cateName; ?>
				</a>
				<span class="ammount-items"><?php echo $category_load->getProductCount(); ?></span>
			</li>
	<?php }  $k++; } ?>
    </ul>
</div>

<div class="rokan-bestseller">		
	<div class="containers">
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				// $showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				// $showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-featured-heading"><h2><?php echo $this->getConfig('title')?></h2>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-featured-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>	
			<div class="row">
				<div class="col-xs-12s">
					<ul class="owl">
						<?php $_collectionSize = $_productCollection->count() ?>
						<?php $i=0; foreach ($_productCollection as $_product): ?>
							<?php if($i %$rows == 0) echo "<li class='item bestsellerslider-item'>"; ?>
								<div class="product-item">
									<?php
									$newFromDate = $_product->getNewsFromDate();
									$newToDate = $_product->getNewsToDate();                 
									$now = date("Y-m-d H:m(worry)");
									// Get the Special Price
									$specialprice = $_product->getSpecialPrice(); 
									// Get the Special Price FROM date
									$specialPriceFromDate = $_product->getSpecialFromDate();
									// Get the Special Price TO date
									$specialPriceToDate = $_product->getSpecialToDate();
									// Get Current date
									?>
									<?php
									$productImage = $block->getImage($_product, $image);
									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									}
									?>
									<div class="besseller_product_item">
										<div class="besel_product-info">
											<?php
												$_productNameStripped = $block->stripTags($_product->getName(), null, true);
											?>
											<strong class="product name product-item-name">
												<a class="product-item-link"
												   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
													<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
												</a>
											</strong>

											
											<div class="besseller_product_info">
												<div class="sale_product"><span class="qty"><?php echo __('10'); ?></span><?php echo __('Sales'); ?></div>
											</div>
										</div>
										<div class="thump_product">
											<div class="product-photo">
												<?php // Product Image ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
													<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1-m');?> 
													<span class="image0_image-switch">
														<?php echo $productImage->toHtml(); ?>
													</span>
													
												</a>
												
											</div>
										</div>
									</div>
								<?php $i++;?>
								</div>
							<?php if($i %$rows == 0) echo "</li>"; ?>                  
						<?php endforeach; ?>
							<?php if($i %$rows != 0) echo "</li>"; ?>                
					</ul>
				</div>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-bestseller .owl").owlCarousel({
						lazyLoad: true,
						autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
						items : <?php echo $default; ?>,
						itemsDesktop : [1399,<?php echo $desktop; ?>],
						itemsDesktopSmall : [991,<?php echo $desktop_small; ?>],
						itemsTablet: [768,<?php echo $tablet; ?>],
						itemsMobile : [479,<?php echo $mobile; ?>],
						slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : <?php if($show_next_back) echo 'true'; else echo 'false'; ?>,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
					    afterAction: function(el){
					     this.$owlItems.removeClass('first-active')
					     this.$owlItems .eq(this.currentItem).addClass('first-active')  
					    }
					});
				});
			</script>
	<?php endif; ?>
	</div>
</div>
<?php } ?>