<div class="top-content-home">
	<div class="banner_mid_h1">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_mid_home1')->toHtml();?>
	</div>
	<div class="besseller_product">	
		<div class="containers">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?>
		</div>
	</div>
	
	<div class="section-element banner_middle">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_friendly')->toHtml();?>
	</div>
	<div class="section-element banner_middles">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle_home2')->toHtml();?>
	</div>
	
	<div class="section-element categories_tab">
		<div class="container">
			<div class="row">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('categories_tab_home1')->toHtml();?>
			</div>
		</div>
	</div>

	<div class="testimonial_box">
		<div class="section_testimonial">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Testimonial\Block\Testimonial')->setTemplate('Rokanthemes_Testimonial::testimonial.phtml')->toHtml();?>
		</div>
		<div class="banner_middle">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle_left')->toHtml();?>
		</div>

	</div>

	<div class="section-element box-blog">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>

	<div class="section-element section-brands">
		<div class="container">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand-logo')->toHtml(); ?>
		</div>
	</div>

</div>
