<div class="top-content-home">
	<div class="container">
		<div class="banner-slider-top slide1">
			<div class="row">
				<div class="col-xs-12 col-sm-9">
					<div class="banner-slider banner-slider1">
						<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage5slider')->toHtml(); ?>
					</div>
				</div>
				<div class="col-xs-12 col-sm-3">
					<div>
						<div class="list-ads5">
							<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('list_ads5')->toHtml(); ?>
						</div>
					</div>
				</div>
			</div>
		 </div>
	</div>


	<div class="section-element categories_tab">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('categories_tab_1_home5')->toHtml();?>
	</div>
	<div class="section-element banner_middles">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_top_home5')->toHtml();?>
	</div>
	<div class="hot-deal">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Superdeals\Block\ProductByCat')->setTemplate('Rokanthemes_Superdeals::category.phtml')->toHtml();?>
		</div>
	</div>
	<div class="section-element banner_middles">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle_home5')->toHtml();?>
	</div>
	<div class="section-element categories_tab_5">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('categories_tab_2_home5')->toHtml();?>
	</div>

	<div class="section-element banner_middles">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle_home2')->toHtml();?>
	</div>

	<div class="group_home4">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-3">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Onsaleproduct\Block\Onsaleproduct')->setTemplate('Rokanthemes_Onsaleproduct::onsaleproduct.phtml')->toHtml();?> 
				</div>
				<div class="col-sm-6 col-md-3">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Featuredpro\Block\Featured')->setTemplate('Rokanthemes_Featuredpro::featured.phtml')->toHtml();?> 
				</div>
				<div class="col-sm-6 col-md-3">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?>  
				</div>
				<div class="col-sm-6 col-md-3">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?> 
				</div>
			</div>
		</div>
	</div>

	<div class="section-element box-blog">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>

</div>
