<?php 
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('itemsDefault');
	$desktop = $this->getConfig('itemsDesktop');
	$desktop_small = $this->getConfig('itemsDesktopSmall');
	$tablet = $this->getConfig('itemsTablet');
	$mobile = $this->getConfig('itemsMobile');
	$show_next_back = $this->getConfig('next_back');
	$show_navigation_control = $this->getConfig('nav_ctrl');

	use Magento\Framework\App\Action\Action;
	if($this->getConfig('enabled')){ // start enable module?>
		<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');	
?>
<div class="rokan-bestseller">		
	<div class="containers">
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				// $showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				// $showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-featured-heading"><h2><?php echo $this->getConfig('title')?></h2>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-featured-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>	
			<div class="rows">
				<div class="col-xs-12s">
					<ul class="owl">
						<?php $_collectionSize = $_productCollection->count() ?>
						<?php $i=0; foreach ($_productCollection as $_product): ?>
							<?php if($i %$rows == 0) echo "<li class='item bestsellerslider-item'>"; ?>
									<?php
									$newFromDate = $_product->getNewsFromDate();
									$newToDate = $_product->getNewsToDate();                 
									$now = date("Y-m-d H:m(worry)");
									// Get the Special Price
									$specialprice = $_product->getSpecialPrice(); 
									// Get the Special Price FROM date
									$specialPriceFromDate = $_product->getSpecialFromDate();
									// Get the Special Price TO date
									$specialPriceToDate = $_product->getSpecialToDate();
									// Get Current date
									?>
									<?php
									$productImage = $block->getImage($_product, $image);
									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									}
									?>
									<div class="group_product_item">
										<div class="thump_product">
											<div class="product-photo">
												<?php // Product Image ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
													<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1-m');?> 
													<span class="image0_image-switch">
														<?php echo $productImage->toHtml(); ?>
													</span>
													
												</a>
												
											</div>
										</div>
										<div class="group_product-info">
											<?php
												$_productNameStripped = $block->stripTags($_product->getName(), null, true);
											?>
											<strong class="product-name">
												<a class="product-item-link"
												   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
													<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
												</a>
											</strong>

											<div class="sale_price">
												<?php if( $this->getConfig('show_price') ): ?>
													 <?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
												<?php endif; ?>
											</div>
											<div class="product-ratting">
												<?php if($this->getConfig('review')): ?>
													<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
												<?php endif; ?>
											</div>
										</div>
										
									</div>
								<?php $i++;?>
							<?php if($i %$rows == 0) echo "</li>"; ?>                  
						<?php endforeach; ?>
							<?php if($i %$rows != 0) echo "</li>"; ?>                
					</ul>
				</div>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-bestseller .owl").owlCarousel({
						lazyLoad: true,
						autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
						items : <?php echo $default; ?>,
						itemsDesktop : [1399,<?php echo $desktop; ?>],
						itemsDesktopSmall : [991,<?php echo $desktop_small; ?>],
						itemsTablet: [767,<?php echo $tablet; ?>],
						itemsMobile : [479,<?php echo $mobile; ?>],
						slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : <?php if($show_next_back) echo 'true'; else echo 'false'; ?>,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
					    afterAction: function(el){
					     this.$owlItems.removeClass('first-active')
					     this.$owlItems .eq(this.currentItem).addClass('first-active')  
					    }
					});
				});
			</script>
	<?php endif; ?>
	</div>
</div>
<?php } ?>