<?php 
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('itemsDefault');
	$desktop = $this->getConfig('itemsDesktop');
	$desktop_small = $this->getConfig('itemsDesktopSmall');
	$tablet = $this->getConfig('itemsTablet');
	$mobile = $this->getConfig('itemsMobile');
	$show_next_back = $this->getConfig('next_back');
	$show_navigation_control = $this->getConfig('nav_ctrl');

	use Magento\Framework\App\Action\Action;
	if($this->getConfig('enabled')){ // start enable module?>
		<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');	
?>
<div class="rokan-bestseller">		
	<div class="containers">
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				// $showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				// $showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-featured-heading"><h2><?php echo $this->getConfig('title')?></h2>
				<p class="description">
					<?php echo $this->getConfig('subtitle')?>
				</p>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-featured-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>	
			<div class="rows">
				<div class="categories_tab">
					<ul class="owl">
						<?php $_collectionSize = $_productCollection->count() ?>
						<?php $i=0; foreach ($_productCollection as $_product): ?>
							<?php if($i %$rows == 0) echo "<li class='item product-item-group'>"; ?>
								<div class="product-item">
									<?php
									$newFromDate = $_product->getNewsFromDate();
									$newToDate = $_product->getNewsToDate();                 
									$now = date("Y-m-d H:m(worry)");
									// Get the Special Price
									$specialprice = $_product->getSpecialPrice(); 
									// Get the Special Price FROM date
									$specialPriceFromDate = $_product->getSpecialFromDate();
									// Get the Special Price TO date
									$specialPriceToDate = $_product->getSpecialToDate();
									// Get Current date
									?>
									<?php
									$productImage = $block->getImage($_product, $image);
									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									}
									?>
									<div class="product-photo">
										<?php // Product Image ?>
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1-m');?> 
											<span class="image0 image-switch">
												<?php echo $productImage->toHtml(); ?>
											</span>
											<span class="image1 image-switch">
												<?php echo $productImageThumb->toHtml(); ?>
											</span>
										</a>
										<?php if ($this->helper('Rokanthemes\QuickView\Helper\Data')->isEnable()){ ?>				
										<div class="quickview-product visible-onhover">
											<a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><i class="lnr lnr-move"></i></a>
										</div>
										<?php } ?>			
										<div class="product-label">
											<?php
												if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)){
													echo "<span class='onsale'>Sale</span>";
													}else{
													if($newFromDate <= $now && $newToDate >= $now) {
														echo "<span class='newlabel'>New</span>";
														//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
													}
												}
											?>	
										</div>
									</div>
									<div class="product-info">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<strong class="product name product-item-name">
										<a class="product-item-link"
										   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</strong>
								
									<?php if( $this->getConfig('show_price') ): ?>
										 <?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
									<?php endif; ?>
									<div class="actions-primary"> 
										<?php if( $this->getConfig('addtowishlist')){?>
													<?php if( $this->getConfig('addtowishlist')): ?>
														<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
														<div class="action-wishlist visible-onhover">
															<a href="#"
															   class="action button towishlist"
															   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
															   data-action="add-to-wishlist"
															   role="button">
																<i class="lnr lnr-heart"></i>
															</a>
														</div>
														<?php endif; ?>
													<?php endif; ?>
											<?php }?>
											<div class="action-add-cart visible-onhover">
												<?php if ($this->getConfig('addtocart')) { ?>
												<div class="actions-primarys"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button type="submit"
																	title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																	class="action tocart primary">
																<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
															</button>
														</form>
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
															<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
														<?php else: ?>
															<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												</div>
												<?php }?>	
											</div>
											<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
											?>
											<div class="action-compare visible-onhover">
												<a href="#"
												   class="action button tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<i class="lnr lnr-layers"></i>
												</a>
											</div>
										</div>	
									</div>								
								<?php $i++;?>
							</div>
							<?php if($i %$rows == 0) echo "</li>"; ?>                  
						<?php endforeach; ?>
							<?php if($i %$rows != 0) echo "</li>"; ?>                
					</ul>
				</div>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-bestseller .owl").owlCarousel({
						lazyLoad: true,
						autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
						items : <?php echo $default; ?>,
						itemsDesktop : [1199,<?php echo $desktop; ?>],
						itemsDesktopSmall : [991,<?php echo $desktop_small; ?>],
						itemsTablet: [768,<?php echo $tablet; ?>],
						itemsMobile : [479,<?php echo $mobile; ?>],
						slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : <?php if($show_next_back) echo 'true'; else echo 'false'; ?>,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
					});
				});
			</script>
	<?php endif; ?>
	</div>
</div>
<?php } ?>