<?php 
	use Magento\Framework\App\Action\Action;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$category_load = $block->getCategory();
	if($category_load && strtotime($block->getConfig('end_date')) >= strtotime($block->getCurrentTime())){ 
		$image = 'category_page_grid-1';
?>
<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-onsale-heading"><h2><?php echo $this->getConfig('title')?></h2>
			</div>
		<?php }?>
<div class="hot-deal-tab-slider hot-deal-tab-slider-customcss">
	<div class="rows">
		<div class="hot-deal-slide">
			<?php 
				$newItems =  $block->getProducts();
			?>
			<?php
			foreach($newItems as $_item) {
			?>
			<div class="hot-deal-tab">
				<div class="col-sm-5 col-xs-12">
					<div class="hot-deal-image">
						<div class="content-item-product product-item">
						
							<div class="product-thumb product-photo">

								<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product-thumb-link">
									<?php 			
									   $productImage = $block->getImage($_item, $image);
									   $productImageThumb = $block->getImage($_item, 'category_page_grid-1');
									 ?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
								
							</div>
						</div>
					</div>
				</div>		
				<div class="col-sm-7 col-xs-12">
					<div class="woocommerce-hot-deal">
						
						<div class="hot-deal-tab-title">
							<h3 class="title-product">
								<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
								   href="<?php echo $block->getProductUrl($_item) ?>"
								   class="product-item-link">
									<?php echo $block->escapeHtml($_item->getName()) ?>
								</a>
							</h3>
						</div>
						
							<div class="info-price">
								<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_item)) ?>
								
							</div>
							<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
								<div class="hot-onsale">
									<span class="onsale">
									<span class="sale-bg"></span>
									<span class="sale-text"><?php echo $block->showLableSalePrice($_item); ?>
									</span>
									</span>
								</div>
							<?php endif; ?>
							<div class="desc"><?php echo $block->softTrim($block->escapeHtml(strip_tags($_item->getShortDescription())), 210); ?></div>
						
						<div class="product-info">
							
							
							<div class="super-deal-countdown" data-date="<?php echo $block->getConfig('end_date');?>"></div>
						</div>
					</div>
				</div>
			</div>
			<?php } ?>
		</div>
	</div>
	
</div>
<script type="text/javascript">
require(["jquery", 'mage/mage','rokanthemes/timecircles', "rokanthemes/owl"], function($){
	'use strict';
    // require([
    //     'jquery',
    //     'rokanthemes/timecircles'
    // ], function ($) {
		$( document ).ready(function() {
			$(".hot-deal-slide").owlCarousel({
	        items: 1,
	         	itemsDesktop : [1366, 1],
		        itemsDesktopSmall : [991, 1],
		        itemsTablet : [767, 1],
		        itemsMobile : [479, 1],
	        navigation : true,
	         afterAction: function(el){
		     this.$owlItems.removeClass('first-active')
		     this.$owlItems .eq(this.currentItem).addClass('first-active')  
		  }
	    });

			if($('.super-deal-countdown').length>0){
				$(".super-deal-countdown").TimeCircles({
					fg_width: 0.01,
					bg_width: 1.2,
					text_size: 0.07,
					circle_bg_color: "#ffffff",
					time: {
						Days: {
							show: true,
							text: " : ",
							color: "#f9bc02"
						},
						Hours: {
							show: true,
							text: " : ",
							color: "#f9bc02"
						},
						Minutes: {
							show: true,
							text: " : ",
							color: "#f9bc02"
						},
						Seconds: {
							show: true,
							text: "",
							color: "#f9bc02"
						}
					}
				}); 
			}
		});
    });
</script>
<?php } ?>